image: registry.gitlab.com/scrumplex/docker-archlinux:latest

build:
  stage: build
  before_script:
    - pacman -Syu --noconfirm --noprogressbar
    - pacman -S --noconfirm --noprogressbar libxnvctrl libxrandr cmake check
  script:
    - cmake -B build -DVIBRANT_ENABLE_TESTS=ON
    - make -C build
  artifacts:
    name: "${CI_BUILD_NAME}"
    expire_in: 1 hour
    paths:
      - build

test:
  stage: test
  dependencies:
    - build
  before_script:
    - pacman -Syu --noconfirm --noprogressbar
    - pacman -S --noconfirm --noprogressbar libxnvctrl libxrandr cmake check
  script:
    - make -C build test
